name: Publish to npm and GitHub

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org
      - run: npm i -g pnpm && pnpm i --filter nextjs-themes
        name: Install dependencies
      - name: Test
        run: ls && cd ./packages/nextjs-themes && pwd && npm test
      - name: Publish to npm
        run: npm build &&  npm publish-package &&  npm publish-package2
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

      - uses: actions/setup-node@v3
        with:
          registry-url: https://npm.pkg.github.com/
      - name: Publish to GitHub Public Repository
        run: cd packages/nextjs-themes &&  npm publish-gpr &&  npm publish-gpr2
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      # Publish lite versions
      - run: node lite.js
      - uses: actions/setup-node@v3
        with:
          registry-url: https://registry.npmjs.org
      - name: Publish to npm
        run: cd packages/nextjs-themes &&  npm build &&  npm publish-package &&  npm publish-package2
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

      - uses: actions/setup-node@v3
        with:
          registry-url: https://npm.pkg.github.com/
      - name: Publish to GitHub Public Repository
        run: cd packages/nextjs-themes &&  npm publish-gpr &&  npm publish-gpr2
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Setup Git
        run: |
          git config --global user.name "mayank1513"
          git config --global user.email "mayank-automate@noreply.github.com"
      - name: patch version and push back to the repo
        run: git reset --hard && git clean -f && npm version patch && git push origin main
