name: Publish to npm and GitHub

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
      - name: Setup Git
        run: |
          git config --global user.name "mayank1513"
          git config --global user.email "mayank-automate@noreply.github.com"
      - run: cd packages/nextjs-themes
      - name: Publish to npm
        run: npm run publish-package && npm run publish-package2
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

      - uses: actions/setup-node@v3
        with:
          registry-url: https://npm.pkg.github.com/
      - name: Publish to GitHub Public Repository
        run: npm run publish-gpr && npm run publish-gpr2
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: patch version and push back to the repo
        run: npm version patch && git push origin main
