name: Publish (NPM & GPR)

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    defaults:
      run:
        working-directory: ./packages/nextjs-themes
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org
      - run: npm i -g pnpm && pnpm i
        name: Install dependencies
      - name: Test
        run: pnpm turbo build --filter persistnsync && npm test
      - name: Setup Git
        run: |
          git config --global user.name "mayank1513"
          git config --global user.email "mayank-automate@noreply.github.com"
          git fetch
          git checkout main
      - name: update version and push back to the repo
        run: pnpm changeset version && git push origin main
        working-directory: .

      - name: Publish persistNsync to NPM
        id: persistNsync
        working-directory: ./packages/persistnsync
        continue-on-error: true
        run: pnpm publish-package && pnpm publish-package2 && pnpm publish-package3
      - uses: actions/setup-node@v3
        if: steps.persistNsync.outcome == 'success'
        with:
          registry-url: https://npm.pkg.github.com/
      - name: Publish to GitHub Public Repository
        if: steps.persistNsync.outcome == 'success'
        working-directory: ./packages/persistnsync
        run: pnpm publish-gpr && pnpm publish-package2 && pnpm publish-package3
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - uses: actions/setup-node@v3
        if: steps.persistNsync.outcome == 'success'
        with:
          registry-url: https://registry.npmjs.org

      - name: Publish nextjs-themes to NPM
        run: pnpm build && pnpm publish-package && pnpm publish-package2
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

      - uses: actions/setup-node@v3
        with:
          registry-url: https://npm.pkg.github.com/
      - name: Publish to GitHub Public Repository
        run: pnpm publish-gpr && pnpm publish-gpr2
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      # Publish lite versions
      - run: node lite.js
      - uses: actions/setup-node@v3
        with:
          registry-url: https://registry.npmjs.org
      - name: Publish to npm
        run: pnpm build && pnpm publish-package && pnpm publish-package2
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

      - uses: actions/setup-node@v3
        with:
          registry-url: https://npm.pkg.github.com/
      - name: Publish to GitHub Public Repository
        run: pnpm publish-gpr && pnpm publish-gpr2
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
