name: Publish to npm and GitHub

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm i -g pnpm && pnpm ci && cd packages/nextjs-themes
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
      - name: Test
        run: pnpm test
      - name: Publish to npm
        run: pnpm build && pnpm publish-package && pnpm publish-package2
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

      - uses: actions/setup-node@v3
        with:
          registry-url: https://npm.pkg.github.com/
      - name: Publish to GitHub Public Repository
        run: pnpm publish-gpr && pnpm publish-gpr2
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      # Publish lite versions
      - run: node lite.js
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
      - name: Publish to npm
        run: pnpm build && pnpm publish-package && pnpm publish-package2
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

      - uses: actions/setup-node@v3
        with:
          registry-url: https://npm.pkg.github.com/
      - name: Publish to GitHub Public Repository
        run: pnpm publish-gpr && pnpm publish-gpr2
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Setup Git
        run: |
          git config --global user.name "mayank1513"
          git config --global user.email "mayank-automate@noreply.github.com"
      - name: patch version and push back to the repo
        run: git reset --hard && git clean -f && npm version patch && git push origin main
