name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./lib/nextjs-themes
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
      - run: npm i -g pnpm && pnpm i
        name: Install dependencies
      - name: Test
        run: npm test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - uses: paambaati/codeclimate-action@v5.0.0
        continue-on-error: true
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageLocations: ./lib/nextjs-themes/coverage/*.xml:clover
